version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MONITORED_USERS=${MONITORED_USERS}
      - REDIS_URL=redis://redis:6379
      - PORT=3001
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: