version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-3001}:3001"
    environment:
      - DISCORD_TOKEN=MTMwNzM4MzIxMTcxMzg5MjQzMg.GnFY6R.dwvVrJ4AXcZklFTWreFJtCajbOIW0x8zxyTMAQ
      - MONITORED_USERS=762055588762877973
      - REDIS_URL=redis://redis:6379
      - PORT=3001
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: